[package]
name = "exc-symbol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = { version = "1" }
parking_lot = { version = "0.12" }
rustc-hash = { version = "1" }
